"""Tests for the per-theme Word reference-doc generator (dev/build tool).

Like ``make_icon``, this script is never imported by the shipping
application (0% coverage before this file existed). It is pure
python-docx -- no Qt -- so it is tested directly. ``main()`` writes into
a hardcoded ``OUT_DIR`` under the real bundled
``_config/_assets/reference_docx``; every test that calls it redirects
``OUT_DIR`` to ``tmp_path`` first so the real, git-tracked .docx files
bundled with the app are never touched or regenerated by a test run.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from docx import Document
from docx.shared import RGBColor

from epy_reports._core._packaging import make_reference_docx as mr
from epy_reports._core.themes_base import Theme

# ---------------------------------------------------------------------------
# Pure helpers
# ---------------------------------------------------------------------------


def test_first_font_extracts_first_family():
    assert mr._first_font('"Calibri", Arial, sans-serif', "X") == "Calibri"


def test_first_font_empty_uses_default():
    assert mr._first_font("", "Georgia") == "Georgia"


def test_pt_parses_a_pt_suffixed_size():
    assert mr._pt("14pt", 11.0) == 14.0


def test_pt_parses_a_bare_number():
    assert mr._pt("14", 11.0) == 14.0


def test_pt_invalid_uses_default():
    assert mr._pt("not-a-size", 11.0) == 11.0


def test_pt_empty_uses_default():
    assert mr._pt("", 11.0) == 11.0


def test_bold_keyword_values():
    assert mr._bold("bold")
    assert mr._bold("bolder")


def test_bold_numeric_weight_threshold():
    assert mr._bold("600")
    assert mr._bold("700")
    assert not mr._bold("400")


def test_bold_invalid_weight_is_false():
    assert not mr._bold("not-a-weight")


def test_rgb_parses_hex_color():
    assert mr._rgb("#FF0010") == RGBColor.from_string("FF0010")


def test_rgb_wrong_length_uses_default():
    assert mr._rgb("#ABC", "112233") == RGBColor.from_string("112233")


def test_rgb_non_hex_characters_use_default():
    """Six characters that are not valid hex digits fall back to default.

    Exercises the ``except ValueError`` branch in ``_rgb``: the length
    check alone (``len(text) != 6``) lets a 6-character non-hex string
    (e.g. from a malformed theme file) through to ``RGBColor.from_string``,
    which is what actually raises.
    """
    assert mr._rgb("#GGGGGG", "445566") == RGBColor.from_string("445566")


def test_rgb_empty_uses_black_default():
    assert mr._rgb("") == RGBColor.from_string("000000")


# ---------------------------------------------------------------------------
# build_reference
# ---------------------------------------------------------------------------


def _theme(css_vars: dict[str, str]) -> Theme:
    return Theme(id="t", display_name="T", qt_palette={}, css_vars=css_vars)


def test_build_reference_writes_a_real_docx(tmp_path: Path):
    theme = _theme({
        "font-family-text": "Calibri, sans-serif",
        "font-family-headings": "Georgia, serif",
        "fg": "#111111", "heading-color": "#003366",
        "h1-size": "28pt", "h1-weight": "700",
    })
    target = tmp_path / "corporate.docx"
    mr.build_reference(theme, target)
    assert target.is_file()
    assert target.stat().st_size > 1_000

    doc = Document(str(target))
    assert doc.styles["Normal"].font.name == "Calibri"
    assert doc.styles["Heading 1"].font.name == "Georgia"
    assert doc.styles["Heading 1"].font.bold is True


def test_build_reference_applies_page_geometry(tmp_path: Path):
    from docx.shared import Inches

    target = tmp_path / "geom.docx"
    mr.build_reference(_theme({}), target)
    doc = Document(str(target))
    section = doc.sections[0]
    assert section.page_width == Inches(8.5)
    assert section.page_height == Inches(11)
    assert section.top_margin == Inches(1)


def test_build_reference_defaults_when_css_vars_are_empty(tmp_path: Path):
    """An empty theme (no css_vars) still produces a valid, styled docx."""
    target = tmp_path / "bare.docx"
    mr.build_reference(_theme({}), target)
    doc = Document(str(target))
    assert doc.styles["Normal"].font.name == "Calibri"


def test_build_reference_heading_color_falls_back_to_fg(tmp_path: Path):
    """No heading-color: headings use the body text colour."""
    target = tmp_path / "fallback.docx"
    mr.build_reference(_theme({"fg": "#204060"}), target)
    doc = Document(str(target))
    assert doc.styles["Heading 1"].font.color.rgb == RGBColor.from_string(
        "204060"
    )


# --- Missing built-in styles: defensive KeyError branches --------------


class _HidingStyles:
    """Wraps a real Styles collection, hiding a chosen set of names.

    Simulates a Document template (a different Word/Pandoc default) that
    lacks one of the "nice to have" styles build_reference re-skins --
    proving the try/except KeyError guards actually degrade gracefully
    instead of crashing, since python-docx's OWN default template always
    ships every style this module touches.
    """

    def __init__(self, real_styles, hidden: set[str]) -> None:
        self._real = real_styles
        self._hidden = hidden

    def __getitem__(self, name: str):
        if name in self._hidden:
            raise KeyError(name)
        return self._real[name]


class _HidingDocument:
    """A python-docx Document with some styles hidden from lookup."""

    def __init__(self, hidden: set[str]) -> None:
        self._real = Document()
        self.sections = self._real.sections
        self.styles = _HidingStyles(self._real.styles, hidden)

    def save(self, path) -> None:
        self._real.save(path)


@pytest.mark.parametrize(
    "hidden",
    [
        {"Body Text", "No Spacing"},
        {"Title", "Subtitle"},
        {"Caption"},
        {"Quote", "Intense Quote"},
    ],
)
def test_build_reference_skips_missing_optional_styles(
    tmp_path, monkeypatch, hidden
):
    """A template missing an optional style is skipped, not fatal."""
    monkeypatch.setattr(mr, "Document", lambda: _HidingDocument(hidden))
    target = tmp_path / "missing_styles.docx"
    mr.build_reference(_theme({}), target)  # must not raise
    assert target.is_file()


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def test_main_writes_one_docx_per_bundled_theme(tmp_path, monkeypatch):
    from epy_reports._core import themes

    monkeypatch.setattr(mr, "OUT_DIR", tmp_path)
    # main() logs each path via target.relative_to(ROOT); ROOT must be an
    # ancestor of the redirected OUT_DIR for that call to succeed.
    monkeypatch.setattr(mr, "ROOT", tmp_path)
    exit_code = mr.main()
    assert exit_code == 0
    for theme_id in themes.THEMES:
        assert (tmp_path / f"{theme_id}.docx").is_file()
